### ISSUE TITLE
inflation module audit

### ISSUE THREAD

**Issue by zsystm** [zsystm/audit-coworking-demo#3]
**Tasks**
- [ ] Review the whole code.
- [ ] Invariant checks
- [ ] SDK Issue
- [ ] Un-patched issue or patch history
- [ ] EVM issues 
- [ ] Possible errors from the codes that tests are not covering
- [ ] Implementations that differ from the SPEC documents
- [ ] (...Any tasks you think should be included)

**Notes**
(...Any notes found during audits you want to share with the team...)
